name = "Slime Grounds"
author = "copygirl"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c55fe8dad2a536fd31c383835a9b941d46e6e1305f8e04f8b33b34432262cc4"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
