name = "Slime Grounds"
author = "copygirl"
version = "1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c989f4dd6afcbb87b8a1631810215100d49f4ad1d6b279ee6d0d03975a689821"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
