name = "CaveBiomeAPI [Forge]"
filename = "cavebiomeapi-1.16.5-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/595/cavebiomeapi-1.16.5-1.4.0.jar"
hash-format = "murmur2"
hash = "680990537"

[update]
[update.curseforge]
file-id = 3489595
project-id = 441706
release-channel = "beta"
