name = "Caves & Cliffs Backport"
filename = "CavesAndCliffsBackport-1.16.5-6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3441/420/CavesAndCliffsBackport-1.16.5-6.3.jar"
hash-format = "murmur2"
hash = "1142857181"

[update]
[update.curseforge]
file-id = 3441420
project-id = 417430
release-channel = "beta"
