name = "FerriteCore (Forge)"
filename = "ferritecore-2.0.7-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3435/176/ferritecore-2.0.7-forge.jar"
hash-format = "murmur2"
hash = "2655477553"

[update]
[update.curseforge]
file-id = 3435176
project-id = 429235
release-channel = "beta"
