name = "Forgery"
filename = "forgery-1.16-1.3.5-rc2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/746/forgery-1.16-1.3.5-rc2.jar"
hash-format = "murmur2"
hash = "2698291501"

[update]
[update.curseforge]
file-id = 3414746
project-id = 434087
release-channel = "beta"
