name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.126.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3488/178/jei-1.16.5-7.7.1.126.jar"
hash-format = "murmur2"
hash = "3537995693"

[update]
[update.curseforge]
file-id = 3488178
project-id = 238222
release-channel = "beta"
